### ISSUE TITLE
US: Clean Code Architecture

### ISSUE THREAD

**Issue by kirtimandwade20** [NeoSOFT-Technologies/rest-java-spring-boot#68]
- [x] Research on Clean Code Architecture
- [x] Compare jhipster with clean code 
- [x] Discussion on finalization of code architecture

**Comment by karthik261099** [comment]
Researched about Clean Code Architecture

**Comment by karthik261099** [comment]
Example: https://github.com/carlphilipp/clean-architecture-example
https://github.com/eugenp/tutorials/tree/master/patterns/clean-architecture/src/main/java/com/baeldung/pattern/cleanarchitecture/usercreation

Medium article: https://medium.com/slalom-build/clean-architecture-with-java-11-f78bba431041
